# Generated by Django 3.1.7 on 2021-03-29 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfirst', '0002_auto_20210329_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='body',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='posts',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
